package api

// ProvisionProfile is one game's provisioning knowledge: everything
// game-shaped that the Raise-a-server wizard and the Ilmari adapter
// interpolate. Core's handlers are game-blind templates; the console's
// wiring assigns a profile next to the Provisioner. This is where the
// knowledge that used to live in each console's agent provisioner mode
// now concentrates — Ilmari itself knows none of it, by contract.
//
// Known extension point (drift ledger, seam 4): games that claim more
// than one contiguous game port (Dragonwilds' UDP pair, Palworld's
// named RCON/REST ports) need a port-arity field and per-game extra
// request fields here. They arrive with those games' port phases.
type ProvisionProfile struct {
	// AgentName brands the stack's service and the container
	// (<AgentName>-<slug>) — "flameagent", "wkagent", "palagent".
	AgentName string
	// ImageRepo is the agent image without its tag.
	ImageRepo string
	// EnvPrefix namespaces the agent's environment (<PREFIX>_TOKEN, …).
	EnvPrefix string
	// DefaultGamePort is the game's own first port: the wizard's default
	// proposal, and the port the container side always binds.
	DefaultGamePort int
	// MountPath is the container-side install mount ("/enshrouded").
	MountPath string
	// SlugFallback names a server whose display name slugifies away
	// entirely — conventionally the game id.
	SlugFallback string
	// StackHeadline finishes the generated stack's first line:
	// "# <name> — <StackHeadline>, generated by …".
	StackHeadline string
	// StackNotes are optional extra header lines (each "# …\n"-shaped)
	// describing what the agent does on first boot for this game.
	StackNotes string
	// GamePortComment annotates the game port mapping line.
	GamePortComment string
}
