package api

// ProvisionProfile is one game's provisioning knowledge: everything
// game-shaped that the Raise-a-server wizard and the Anvil adapter
// interpolate. Core's handlers are game-blind templates; the console's
// wiring assigns a profile next to the Provisioner. This is where the
// knowledge that used to live in each console's agent provisioner mode
// now concentrates — Anvil itself knows none of it, by contract.
//
// Every seam-4 variance is now expressed here: port-run arity
// (Dragonwilds' pair), required owner identity, and named TCP admin
// transports (Palworld's REST/RCON trio).
type ProvisionProfile struct {
	// AgentName brands the stack's service and the container
	// (<AgentName>-<slug>) — "flameagent", "wkagent", "palagent".
	AgentName string
	// ImageRepo is the agent image without its tag.
	ImageRepo string
	// EnvPrefix namespaces the agent's environment (<PREFIX>_TOKEN, …).
	EnvPrefix string
	// DefaultGamePort is the game's own first port: the wizard's default
	// proposal, and the port the container side always binds.
	DefaultGamePort int
	// MountPath is the container-side install mount ("/enshrouded").
	MountPath string
	// SlugFallback names a server whose display name slugifies away
	// entirely — conventionally the game id.
	SlugFallback string
	// StackHeadline finishes the generated stack's first line:
	// "# <name> — <StackHeadline>, generated by …".
	StackHeadline string
	// StackNotes are optional extra header lines (each "# …\n"-shaped)
	// describing what the agent does on first boot for this game.
	StackNotes string
	// GamePortComment annotates the game port mapping line.
	GamePortComment string
	// GamePortCount is how many contiguous UDP ports the game claims
	// from GamePort (Dragonwilds binds a pair). Zero means one.
	GamePortCount int
	// OwnerIDRequired refuses provisioning without an ownerId — for
	// games that will not start without an in-game owner. OwnerIDHelp
	// finishes the refusal ("in-game: Settings, …").
	OwnerIDRequired bool
	OwnerIDHelp     string
	// AdminPorts are named TCP admin transports the game exposes beside
	// the game port (Palworld's REST + RCON). Each becomes a wizard
	// field (<key>Port), a stack and Anvil mapping, a port-proposal
	// entry, and — for the well-known keys "rest" and "rcon" — the
	// server row's transport wiring.
	AdminPorts []AdminPort
}

// AdminPort is one named TCP admin transport.
type AdminPort struct {
	// Key is the stable id ("rest", "rcon") — the wizard request field
	// is <key>Port and the proposal entry uses the key.
	Key string
	// Container is the container-side port the game binds (8212, 25575).
	Container int
	// Default is the default published host port.
	Default int
	// Comment annotates the stack mapping line.
	Comment string
}

func (p *ProvisionProfile) adminPort(key string) *AdminPort {
	for i := range p.AdminPorts {
		if p.AdminPorts[i].Key == key {
			return &p.AdminPorts[i]
		}
	}
	return nil
}

func (p *ProvisionProfile) portCount() int {
	if p.GamePortCount < 1 {
		return 1
	}
	return p.GamePortCount
}
