package api

// ProvisionProfile is one game's provisioning knowledge: everything
// game-shaped that the Raise-a-server wizard and the Ilmari adapter
// interpolate. Core's handlers are game-blind templates; the console's
// wiring assigns a profile next to the Provisioner. This is where the
// knowledge that used to live in each console's agent provisioner mode
// now concentrates — Ilmari itself knows none of it, by contract.
//
// Known extension point (drift ledger, seam 4): Palworld's named
// RCON/REST port trio arrives with its port phase.
type ProvisionProfile struct {
	// AgentName brands the stack's service and the container
	// (<AgentName>-<slug>) — "flameagent", "wkagent", "palagent".
	AgentName string
	// ImageRepo is the agent image without its tag.
	ImageRepo string
	// EnvPrefix namespaces the agent's environment (<PREFIX>_TOKEN, …).
	EnvPrefix string
	// DefaultGamePort is the game's own first port: the wizard's default
	// proposal, and the port the container side always binds.
	DefaultGamePort int
	// MountPath is the container-side install mount ("/enshrouded").
	MountPath string
	// SlugFallback names a server whose display name slugifies away
	// entirely — conventionally the game id.
	SlugFallback string
	// StackHeadline finishes the generated stack's first line:
	// "# <name> — <StackHeadline>, generated by …".
	StackHeadline string
	// StackNotes are optional extra header lines (each "# …\n"-shaped)
	// describing what the agent does on first boot for this game.
	StackNotes string
	// GamePortComment annotates the game port mapping line.
	GamePortComment string
	// GamePortCount is how many contiguous UDP ports the game claims
	// from GamePort (Dragonwilds binds a pair). Zero means one.
	GamePortCount int
	// OwnerIDRequired refuses provisioning without an ownerId — for
	// games that will not start without an in-game owner. OwnerIDHelp
	// finishes the refusal ("in-game: Settings, …").
	OwnerIDRequired bool
	OwnerIDHelp     string
}

func (p *ProvisionProfile) portCount() int {
	if p.GamePortCount < 1 {
		return 1
	}
	return p.GamePortCount
}
