package api

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/safwyls/palcon/internal/palagent"
	"github.com/safwyls/palcon/internal/store"
)

// Provisioning ("new server from the dashboard", docs/sidecar-agent.md
// phase 4): palcon deliberately holds no docker create rights, so this
// endpoint does everything short of the paste — it registers a fully
// wired server row (host, ports, REST/RCON password, agent URL + token)
// and generates the matching supervisor-mode stack file. The human
// deploys the stack; the agent installs the game on first boot and the
// server comes up already manageable (PALAGENT_ADMIN_PASSWORD enforces
// the REST/RCON interfaces on).

type provisionRequest struct {
	Name string `json:"name"`
	// Host is where the stack will run — an address palcon can reach the
	// published ports on.
	Host string `json:"host"`
	// DataPath is the host directory mounted as the install volume.
	DataPath string `json:"dataPath"`
	// Published host ports; the in-container ports stay at the game's
	// defaults (8211/8212/25575) and the agent's 8811.
	GamePort  int `json:"gamePort"`
	RESTPort  int `json:"restPort"`
	RCONPort  int `json:"rconPort"`
	AgentPort int `json:"agentPort"`
	// ImageTag selects the palagent channel; default latest.
	ImageTag string `json:"imageTag"`
	// AdminPassword is generated when blank.
	AdminPassword string `json:"adminPassword"`
	// ServerName/ServerDesc become the in-game ServerName and
	// ServerDescription (MOTD), seeded once on first boot — later edits in
	// the settings editor stick. Name defaults to the palcon display name.
	ServerName string `json:"serverName"`
	ServerDesc string `json:"serverDesc"`
	// RunAs is the container user:group; defaults to the TrueNAS apps
	// user 568:568. Empty string is normalized to the default; "root"
	// omits the user line entirely.
	RunAs string `json:"runAs"`
}

var runAsPattern = regexp.MustCompile(`^\d{1,7}:\d{1,7}$`)

func randomHex(n int) string {
	b := make([]byte, n)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

func (s *Server) handleProvisionServer(w http.ResponseWriter, r *http.Request) {
	var req provisionRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid request body")
		return
	}
	req.Name = strings.TrimSpace(req.Name)
	req.Host = strings.TrimSpace(req.Host)
	req.DataPath = strings.TrimSpace(req.DataPath)
	switch {
	case req.Name == "":
		writeError(w, http.StatusBadRequest, "name is required")
		return
	case req.Host == "":
		writeError(w, http.StatusBadRequest, "host is required — the address palcon will reach the server on")
		return
	case req.DataPath == "" || !filepath.IsAbs(req.DataPath):
		writeError(w, http.StatusBadRequest, "data path must be an absolute host path for the install volume")
		return
	}
	if req.GamePort == 0 {
		req.GamePort = 8211
	}
	if req.RESTPort == 0 {
		req.RESTPort = 8212
	}
	if req.RCONPort == 0 {
		req.RCONPort = 25575
	}
	if req.AgentPort == 0 {
		req.AgentPort = 8811
	}
	seen := map[int]bool{}
	for _, p := range []int{req.GamePort, req.RESTPort, req.RCONPort, req.AgentPort} {
		if p < 1 || p > 65535 || seen[p] {
			writeError(w, http.StatusBadRequest, "ports must be distinct and in 1-65535")
			return
		}
		seen[p] = true
	}
	if req.ImageTag == "" {
		req.ImageTag = "latest"
	}
	if req.AdminPassword == "" {
		req.AdminPassword = randomHex(10)
	}
	if req.ServerName == "" {
		req.ServerName = req.Name
	}
	switch {
	case req.RunAs == "":
		req.RunAs = "568:568"
	case req.RunAs == "root":
		req.RunAs = ""
	case !runAsPattern.MatchString(req.RunAs):
		writeError(w, http.StatusBadRequest, `run-as must be numeric uid:gid (or "root")`)
		return
	}
	token := randomHex(24)

	srv := &store.Server{
		Name: req.Name, Host: req.Host,
		RCONPort: req.RCONPort, RCONPassword: req.AdminPassword,
		RESTPort: req.RESTPort, RESTPassword: req.AdminPassword,
		GamePort: req.GamePort,
		UseREST:  true, Enabled: true,
		AgentURL:   fmt.Sprintf("http://%s:%d", req.Host, req.AgentPort),
		AgentToken: token,
	}
	id, err := s.store.CreateServer(r.Context(), srv)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to create server")
		return
	}
	srv.ID = id
	s.audit(r, id, "server-provision", srv.Name)

	userLine := ""
	if req.RunAs != "" {
		userLine = fmt.Sprintf(`    # The data path must be owned (or writable) by this user.
    user: "%s"
`, req.RunAs)
	}
	identityEnv := fmt.Sprintf("      PALAGENT_SERVER_NAME: %q\n", req.ServerName)
	if req.ServerDesc != "" {
		identityEnv += fmt.Sprintf("      PALAGENT_SERVER_DESC: %q\n", req.ServerDesc)
	}

	stack := fmt.Sprintf(`# %s — Palworld server supervised by palagent, generated by palcon.
# Deploy as its own stack (TrueNAS custom app / docker compose). On first
# boot the agent installs the game via SteamCMD — watch progress from the
# server's dashboard card — and starts it already wired for REST/RCON.
services:
  palagent:
    image: ghcr.io/safwyls/palagent:%s
%s    environment:
      # SteamCMD needs a writable home; the run-as user has none in the image.
      HOME: /tmp
      PALAGENT_MODE: supervisor
      PALAGENT_TOKEN: %s
      PALAGENT_ADMIN_PASSWORD: %s
%s    ports:
      - "%d:8211/udp"   # game
      - "%d:8212"       # REST (dashboard)
      - "%d:25575"      # RCON (dashboard fallback)
      - "%d:8811"       # palagent API
    volumes:
      - %s:/palworld
    restart: unless-stopped
`, req.Name, req.ImageTag, userLine, token, req.AdminPassword, identityEnv,
		req.GamePort, req.RESTPort, req.RCONPort, req.AgentPort, req.DataPath)

	// One-click (phase 5): when a provisioner is configured, deploy the
	// stack now. A failed deploy is reported but not fatal — the row and
	// the stack file remain, and the operator can fall back to pasting.
	deployed := false
	deployError := ""
	dataDir := ""
	if s.Provisioner != nil {
		result, err := s.Provisioner.Provision(r.Context(), palagent.ProvisionRequest{
			Slug:          slugify(req.Name),
			ImageTag:      req.ImageTag,
			Token:         token,
			AdminPassword: req.AdminPassword,
			ServerName:    req.ServerName,
			ServerDesc:    req.ServerDesc,
			RunAs:         req.RunAs,
			GamePort:      req.GamePort,
			RESTPort:      req.RESTPort,
			RCONPort:      req.RCONPort,
			AgentPort:     req.AgentPort,
		})
		if err != nil {
			deployError = err.Error()
			s.logger.Error("provisioner deploy failed", "server", srv.Name, "error", err)
		} else {
			deployed = true
			dataDir = result.DataDir
			s.audit(r, id, "server-deploy", result.Container)
			s.logger.Info("provisioner deployed server", "server", srv.Name, "container", result.Container)
		}
	}

	writeJSON(w, http.StatusCreated, map[string]any{
		"server":        toDTO(srv),
		"adminPassword": req.AdminPassword,
		"agentToken":    token,
		"stack":         stack,
		"deployed":      deployed,
		"deployError":   deployError,
		"dataDir":       dataDir,
	})
}

// slugify reduces a display name to a container/directory-safe slug.
func slugify(name string) string {
	slug := strings.ToLower(name)
	slug = regexp.MustCompile(`[^a-z0-9]+`).ReplaceAllString(slug, "-")
	slug = strings.Trim(slug, "-")
	if slug == "" {
		slug = "palworld"
	}
	if len(slug) > 40 {
		slug = slug[:40]
	}
	return strings.Trim(slug, "-")
}
