package api

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"path/filepath"
	"strings"

	"github.com/safwyls/palcon/internal/store"
)

// Provisioning ("new server from the dashboard", docs/sidecar-agent.md
// phase 4): palcon deliberately holds no docker create rights, so this
// endpoint does everything short of the paste — it registers a fully
// wired server row (host, ports, REST/RCON password, agent URL + token)
// and generates the matching supervisor-mode stack file. The human
// deploys the stack; the agent installs the game on first boot and the
// server comes up already manageable (PALAGENT_ADMIN_PASSWORD enforces
// the REST/RCON interfaces on).

type provisionRequest struct {
	Name string `json:"name"`
	// Host is where the stack will run — an address palcon can reach the
	// published ports on.
	Host string `json:"host"`
	// DataPath is the host directory mounted as the install volume.
	DataPath string `json:"dataPath"`
	// Published host ports; the in-container ports stay at the game's
	// defaults (8211/8212/25575) and the agent's 8811.
	GamePort  int `json:"gamePort"`
	RESTPort  int `json:"restPort"`
	RCONPort  int `json:"rconPort"`
	AgentPort int `json:"agentPort"`
	// ImageTag selects the palagent channel; default latest.
	ImageTag string `json:"imageTag"`
	// AdminPassword is generated when blank.
	AdminPassword string `json:"adminPassword"`
}

func randomHex(n int) string {
	b := make([]byte, n)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

func (s *Server) handleProvisionServer(w http.ResponseWriter, r *http.Request) {
	var req provisionRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid request body")
		return
	}
	req.Name = strings.TrimSpace(req.Name)
	req.Host = strings.TrimSpace(req.Host)
	req.DataPath = strings.TrimSpace(req.DataPath)
	switch {
	case req.Name == "":
		writeError(w, http.StatusBadRequest, "name is required")
		return
	case req.Host == "":
		writeError(w, http.StatusBadRequest, "host is required — the address palcon will reach the server on")
		return
	case req.DataPath == "" || !filepath.IsAbs(req.DataPath):
		writeError(w, http.StatusBadRequest, "data path must be an absolute host path for the install volume")
		return
	}
	if req.GamePort == 0 {
		req.GamePort = 8211
	}
	if req.RESTPort == 0 {
		req.RESTPort = 8212
	}
	if req.RCONPort == 0 {
		req.RCONPort = 25575
	}
	if req.AgentPort == 0 {
		req.AgentPort = 8811
	}
	seen := map[int]bool{}
	for _, p := range []int{req.GamePort, req.RESTPort, req.RCONPort, req.AgentPort} {
		if p < 1 || p > 65535 || seen[p] {
			writeError(w, http.StatusBadRequest, "ports must be distinct and in 1-65535")
			return
		}
		seen[p] = true
	}
	if req.ImageTag == "" {
		req.ImageTag = "latest"
	}
	if req.AdminPassword == "" {
		req.AdminPassword = randomHex(10)
	}
	token := randomHex(24)

	srv := &store.Server{
		Name: req.Name, Host: req.Host,
		RCONPort: req.RCONPort, RCONPassword: req.AdminPassword,
		RESTPort: req.RESTPort, RESTPassword: req.AdminPassword,
		UseREST: true, Enabled: true,
		AgentURL:   fmt.Sprintf("http://%s:%d", req.Host, req.AgentPort),
		AgentToken: token,
	}
	id, err := s.store.CreateServer(r.Context(), srv)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to create server")
		return
	}
	srv.ID = id
	s.audit(r, id, "server-provision", srv.Name)

	stack := fmt.Sprintf(`# %s — Palworld server supervised by palagent, generated by palcon.
# Deploy as its own stack (TrueNAS custom app / docker compose). On first
# boot the agent installs the game via SteamCMD — watch progress from the
# server's dashboard card — and starts it already wired for REST/RCON.
services:
  palagent:
    image: ghcr.io/safwyls/palagent:%s
    environment:
      PALAGENT_MODE: supervisor
      PALAGENT_TOKEN: %s
      PALAGENT_ADMIN_PASSWORD: %s
    ports:
      - "%d:8211/udp"   # game
      - "%d:8212"       # REST (dashboard)
      - "%d:25575"      # RCON (dashboard fallback)
      - "%d:8811"       # palagent API
    volumes:
      - %s:/palworld
    restart: unless-stopped
`, req.Name, req.ImageTag, token, req.AdminPassword,
		req.GamePort, req.RESTPort, req.RCONPort, req.AgentPort, req.DataPath)

	writeJSON(w, http.StatusCreated, map[string]any{
		"server":        toDTO(srv),
		"adminPassword": req.AdminPassword,
		"agentToken":    token,
		"stack":         stack,
	})
}
