package dwconfig

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// sample mirrors the shape seen in community DedicatedServer.ini captures:
// a UE section header, bare string values with spaces, ints, a bool, a
// comment, and one deliberately duplicated key standing in for UE's array
// (+Key=) convention.
const sample = `; generated by the game
[/Script/RSDragonwilds.DWServerSettings]
ServerName=Grimwood Bastion
DefaultWorldName=Ashenfall-Prime
OwnerID=abc123-def
AdminPassword=hunter2
MaxPlayers=6
Port=7777
AutosaveInterval=600.5
EnableMods=True
ModList=first
ModList=second
`

func writeSample(t *testing.T, content string) string {
	t.Helper()
	dir := t.TempDir()
	file := filepath.Join(dir, "DedicatedServer.ini")
	if err := os.WriteFile(file, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return file
}

func settingByKey(t *testing.T, res *Result, key string) Setting {
	t.Helper()
	for _, s := range res.Settings {
		if s.Key == key {
			return s
		}
	}
	t.Fatalf("setting %q not found", key)
	return Setting{}
}

func TestReadClassifiesFromWrittenForm(t *testing.T) {
	file := writeSample(t, sample)
	res, err := Read(file)
	if err != nil {
		t.Fatal(err)
	}
	if !res.Writable {
		t.Error("expected writable temp file")
	}
	cases := map[string][2]string{
		"ServerName":       {"string", "Grimwood Bastion"},
		"MaxPlayers":       {"int", "6"},
		"AutosaveInterval": {"float", "600.5"},
		"EnableMods":       {"bool", "True"},
	}
	for key, want := range cases {
		s := settingByKey(t, res, key)
		if s.Type != want[0] || s.Value != want[1] {
			t.Errorf("%s = (%s, %q), want (%s, %q)", key, s.Type, s.Value, want[0], want[1])
		}
		if s.Section != "/Script/RSDragonwilds.DWServerSettings" {
			t.Errorf("%s section = %q", key, s.Section)
		}
	}
	// The duplicated array key is not served as an editable setting.
	for _, s := range res.Settings {
		if s.Key == "ModList" {
			t.Error("duplicated key ModList should be hidden from the editor")
		}
	}
}

func TestReadResolvesPlatformFolders(t *testing.T) {
	dir := t.TempDir()
	sub := filepath.Join(dir, "LinuxServer")
	if err := os.MkdirAll(sub, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(sub, "DedicatedServer.ini"), []byte(sample), 0o644); err != nil {
		t.Fatal(err)
	}
	res, err := Read(dir)
	if err != nil {
		t.Fatal(err)
	}
	if got := settingByKey(t, res, "Port"); got.Value != "7777" {
		t.Errorf("Port = %q", got.Value)
	}
}

func TestWriteEditsInPlaceAndKeepsEverythingElse(t *testing.T) {
	file := writeSample(t, sample)
	err := Write(file, map[string]string{
		"ServerName": "New Name With Spaces",
		"MaxPlayers": "4",
		"EnableMods": "off",
	})
	if err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(file)
	if err != nil {
		t.Fatal(err)
	}
	text := string(got)
	for _, want := range []string{
		"; generated by the game",
		"[/Script/RSDragonwilds.DWServerSettings]",
		"ServerName=New Name With Spaces",
		"MaxPlayers=4",
		"EnableMods=False",
		"AdminPassword=hunter2",
		"ModList=first",
		"ModList=second",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("missing %q in:\n%s", want, text)
		}
	}
	// One-level undo exists and holds the pre-edit contents.
	bak, err := os.ReadFile(file + ".flamekeeper.bak")
	if err != nil {
		t.Fatalf("backup: %v", err)
	}
	if string(bak) != sample {
		t.Error("backup does not match original contents")
	}
}

func TestWritePreservesCRLF(t *testing.T) {
	crlf := strings.ReplaceAll(sample, "\n", "\r\n")
	file := writeSample(t, crlf)
	if err := Write(file, map[string]string{"MaxPlayers": "3"}); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(file)
	if !strings.Contains(string(got), "MaxPlayers=3\r\n") {
		t.Error("CRLF line ending not preserved on edited line")
	}
	if strings.Contains(string(got), "ServerName=Grimwood Bastion\n[") {
		t.Error("unedited lines lost their CR")
	}
}

func TestWriteRejections(t *testing.T) {
	file := writeSample(t, sample)
	cases := []struct {
		name    string
		changes map[string]string
	}{
		{"unknown key", map[string]string{"NoSuchKey": "1"}},
		{"duplicated key", map[string]string{"ModList": "third"}},
		{"bad int", map[string]string{"MaxPlayers": "lots"}},
		{"bad bool", map[string]string{"EnableMods": "maybe"}},
		{"newline injection", map[string]string{"ServerName": "a\nEvil=1"}},
	}
	before, _ := os.ReadFile(file)
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if err := Write(file, tc.changes); err == nil {
				t.Fatal("expected error")
			}
			after, _ := os.ReadFile(file)
			if string(after) != string(before) {
				t.Error("file changed despite rejected edit")
			}
		})
	}
}

func TestRotateAdminPassword(t *testing.T) {
	file := writeSample(t, sample)
	if err := RotateAdminPassword(file, "s3cret!"); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(file)
	if !strings.Contains(string(got), "AdminPassword=s3cret!") {
		t.Error("password not rotated")
	}
	if err := RotateAdminPassword(file, "  "); err == nil {
		t.Error("expected refusal of empty password")
	}
	// Never-add policy: a file without the key refuses rather than appends.
	bare := writeSample(t, "ServerName=x\n")
	if err := RotateAdminPassword(bare, "pw"); err == nil {
		t.Error("expected error when AdminPassword key is absent")
	}
}

func TestReadNotConfigured(t *testing.T) {
	if _, err := Read(""); err != ErrNotConfigured {
		t.Fatalf("err = %v, want ErrNotConfigured", err)
	}
}
